Repository Mishasama/ProjectZomboidTranslations, pull requests merged in 2020-03, with the labels that each got.

#40 AIMEIXIZI
  CN/IG_UI_CN.txt
  CN/Sandbox_CN.txt
  CN/Tooltip_CN.txt
  CODEOWNERS
  EN/IG_UI_EN.txt
  EN/Sandbox_EN.txt
  EN/Tooltip_EN.txt
  EN/UI_EN.txt
  ES/DynamicRadio_ES.txt
  ES/Items_ES.txt
  ES/Recipes_ES.txt
  ES/Sandbox_ES.txt
  ES/Tooltip_ES.txt
  README.md
Labels: enhancement

#42 Update DynamicRadio_CN.txt
  CN/DynamicRadio_CN.txt
Labels: bug

#44 English minor changes …
  CN/DynamicRadio_CN.txt
  CN/IG_UI_CN.txt
  CN/Items_CN.txt
  CN/Sandbox_CN.txt
  CN/Tooltip_CN.txt
  CN/UI_CN.txt
  EN/ContextMenu_EN.txt
  EN/IG_UI_EN.txt
  EN/Stash_EN.txt
  EN/UI_EN.txt
  ES/ContextMenu_ES.txt
  ES/IG_UI_ES.txt
  ES/UI_ES.txt
  PL/Challenge_PL.txt
  PL/ContextMenu_PL.txt
  PL/DynamicRadio_PL.txt
  PL/IG_UI_PL.txt
  PL/Items_PL.txt
  PL/Moveables_PL.txt
  PL/Recipes_PL.txt
  PL/Sandbox_PL.txt
  PL/Stash_PL.txt
  PL/Tooltip_PL.txt
  PL/UI_PL.txt
Labels: documentation, enhancement

#43 Patch 1
  EN/DynamicRadio_EN.txt
  ES/ContextMenu_ES.txt
  ES/IG_UI_ES.txt
  ES/UI_ES.txt
  PL/Challenge_PL.txt
  PL/ContextMenu_PL.txt
  PL/DynamicRadio_PL.txt
  PL/IG_UI_PL.txt
  PL/Items_PL.txt
  PL/Recipes_PL.txt
  PL/Sandbox_PL.txt
  PL/Tooltip_PL.txt
  PL/UI_PL.txt
Labels: bug
